### ISSUE TITLE
关于暗夜模式的一些问题

### ISSUE THREAD

**Issue by umumd** [YunYouJun/sponsors#2]
君君，今天偶尔上来浏览你的作品，其中sponsors.yunyoujun.cn这个的暗夜模式看起来有点智障 ，因为切换到暗夜模式后捐款列表的背景还是白色的，然后中心的logo也还是黑色的（在黑色背景下看不出来），十分突兀，望改进。

最后，兜兜转转看了下，不得不承认你的作品有点赏心悦目。

问题截图如下：

开启暗夜模式之前：
![image](https://user-images.githubusercontent.com/62042997/147739645-755b631d-d2c9-4b26-938d-727d0698f5ac.png)

开启后：
![image](https://user-images.githubusercontent.com/62042997/147739689-c746c4f7-6b22-40e5-92b7-dcd5f6d81357.png)

**Comment by YunYouJun** [comment]
感谢您的反馈。毫无疑问，暗色模式还没有优化。表格部分目前使用的是 Element Plus，而其暂时还没有支持暗色模式。（这在 element 的下一步计划中，我会尽快推进该项实现）。

**Comment by YunYouJun** [comment]
现在支持了！
